spring:
  profiles:
    active: dev  # 기본 프로필 설정

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: zaSO02h44LV/fZ7/OvdLXjKYOmdkEt3g0C3sQJdL0qxJHo7UyWOCNtlRy+UBfmDCNw7JyuMoB8j+WxA9g80FLA==
  expiration: 86400000
  header: Authorization
  prefix: Bearer

server:
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    
logging:
  level:
    org.mybatis: DEBUG
    com.br.brlog: DEBUG